name: raise-pr
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      env_name:
        required: true
        type: string

jobs:
  raise-pr:
    runs-on: ubuntu-20.04
    name: infra
    steps:
    - name: Check output
      run: |
        echo "ENV NAME =${{ inputs.env_name }}"
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: source
    - name: Set the env var 'REPOSITORY_NAME'
      run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
      shell: bash
    - name: Checkout infra repo
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository_owner }}/infra
        path: infra
        token: ${{ secrets.GH_PAT }}
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      env:
        ImageOS: ubuntu18
      with:
        ruby-version: 2.7
    - name: Generate changelog
      id: changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        OCTOCAM_GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        REPO_OWNER: ${{ github.repository_owner }}
      working-directory: source
      run: |
        COMMIT_FROM=$(git rev-list --max-parents=0 HEAD)
        PR_FROM=$(date -d "@$(git show -s --format=%ct $COMMIT_FROM)" --iso-8601=seconds)
        PR_TO=$(date --iso-8601=seconds)
        gem install octocam
        octocam -o $REPO_OWNER -r $REPOSITORY_NAME -f $PR_FROM -t $PR_TO > ../CHANGELOG.md
    - uses: imranismail/setup-kustomize@master
      with:
        kustomize-version: "3.9.2"
    - name: Create PR
      env:
        TARGET_PROJECT: k8s/overlays
        TARGET_ENV: nonprod/${{ inputs.env_name }}
        TARGET_BRANCH: master
        GITHUB_USERNAME: ${{ secrets.GH_BOT_UNAME }}
        GITHUB_EMAIL: ${{ secrets.GH_BOT_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        APP_VERSION: ${{ inputs.image_tag }}
        IMAGE_REGISTRY: jed.ocir.io/fr9ckauowgwh
      run: |
        # NON-PRODUCTION: DEV/STG/UAT (1-n)
        if [[ "${{ inputs.env_name }}" =~ (dev|stg|uat) ]]; then
          INPUT_ENV_NAME=${{ inputs.env_name }}
          TARGET_PROJECT=k8s/overlays
          TARGET_ENV=nonprod/${{ inputs.env_name }}
          TARGET_BRANCH=master
          echo "INSIDE IF NON PROD : ${{ inputs.env_name }}  "
        fi

        # PRODUCTION
        if [[ "${{ inputs.env_name }}" == "production" ]]; then
          TARGET_ENV=production/apps
          TARGET_PROJECT=env-setup/k8s/overlays
          TARGET_BRANCH=master
        fi

        echo "OUTSIDE  : ${{ inputs.env_name }}  "
        source/.github/workflows/raise-pr.sh
